version: 2
jobs:
  test:
    docker:
      - image: dkarnikis/test:latest
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference

    steps:
      - checkout
      - run: cd /pash;git checkout top-level-tests
      - run: echo 'Running tests'
      - run: echo $PWD
      - run: cd /pash;bash ./run_tests.sh > results.log 2>&1
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory
          root: /pash
          # Must be relative path from root
          paths:
            - results.log

  comment:
    docker:
      - image: dkarnikis/test:latest
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference

    steps:
      - checkout
      - attach_workspace:
            at: /pash
      - run: echo $PWD
      - run: bash .c;


workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - comment:
            requires:
                - test
      #  requires:
      #      - build
      #- test:
      #    requires:
      #      - build

