version: 2
jobs:
  test:
    docker:
      - image: dkarnikis/test:latest
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference

    steps:
      - checkout
        - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory
          root: /
          # Must be relative path from root
          paths:
            - pash
      - run: cd /pash
      - run: git checkout top-level-tests
      - run: echo 'Running tests'
      - run: echo $PWD
      - run: bash ./run_tests.sh > results.log 2>&1
      - run: echo "Trying out workspaces" > my_workspace/echo-output


  comment:
    docker:
      - image: dkarnikis/test:latest
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference

    steps:
      - checkout
      - attach_workspace:
            at: /root/project/pash
      - run: echo $PWD
      - run: bash .c;


workflows:
  version: 2
  build_and_test:
    jobs:
      - test:
      - comment:
            requires:
                - test
      #  requires:
      #      - build
      #- test:
      #    requires:
      #      - build

