name: Pash-Benchmark-Tests

# execute the workflow only when we are pushing on a pull request 
on: 
  pull_request:
    types: [assigned, opened, synchronize, reopened]

  workflow_dispatch:
# Jobs section
jobs:
    Pash-Tests:
      strategy:
        matrix:
          os: 
            - ubuntu-18.04
            - ubuntu-20.04
            #- debian #stable-20210408
      runs-on: ${{ matrix.os }}
            
      steps:
        - uses: actions/checkout@v2 
        - name: Create comment
          uses: peter-evans/create-pull-request@v3
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
        - name: Check outputs
          run: |
            echo "Pull Request Number "
            #echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
