name: Pash-Benchmark-Tests

# execute the workflow only when we are pushing on a pull request 
on: 
  pull_request:
    types: [assigned, opened, synchronize, reopened]
    # we should add all the paths that we should ignore 
#    paths-ignore:
#      - "docs/**"
#      - "**/.github/workflows/main.yml"
#      - '**/README.md'
#  push:
#    branches:
#      - '*'
#      - '!master'
#    paths-ignore:
#      - "docs/**"
#      - "**/.github/workflows/main.yml"
#      - '**/README.md'

    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Jobs section
jobs:
    Pash-Tests:
        runs-on: ubuntu-18.04
        steps:
          - uses: actions/checkout@v2 
            # Fetches the latest changes and executes all the benchmarks
          - name: Running-Pash-Benchmarks
            run: |
              echo 'hello world'
          # We post the results on the corresponding pull request thread
          - name: Posting Results
            uses: unsplash/comment-on-pr@master
            if: github.ref != 'refs/heads/main'
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            with:
              msg: "${{ env.VERSION }}"
              check_for_duplicate_msg: false
