# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Jobs section
jobs:
    # The job that will use the container image you just pushed to ghcr.io
    super-job:
        runs-on: ubuntu-18.04
        container:
            image: dkarnikis/test:latest

        steps:
            - name: super-step
              shell: bash
              run: |
                ls
                ls /
                ls ~/
                echo "--This is running in my custom Docker image--"
