name: Pash-Benchmark-Tests
on: 
pull_request_target:
  types: [assigned, opened, synchronize, reopened]



  paths: 
        - compiler/**
        - runtime/**
        - evaluation/**
        - annotations/**

workflow_dispatch:
  # Jobs section
jobs:
  build:
      runs-on: ubuntu-20.04 #${{ matrix.os }}
      steps:
        - name: Checkout git repo
        uses: actions/checkout@v2
        with:
          repository: ${{ steps.head_repo_name.outputs.repo }}
          fetch-depth: 0
        run: |
          # get the timer in english
          date=$(LANG=en_us_88591; date)
          echo "VERSION<<EOF" >> $GITHUB_ENV
          echo  "OS:${{matrix.os}}" >> $GITHUB_ENV
          echo -e "$date\n" >> $GITHUB_ENV
          # Parses the results and construct a github message post
          # we append the data to the global env
          cat results.log >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
        - name: Comment on PR
        uses: actions/github-script@v3
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '${{ env.VERSION}}',
            })
      - name: Exit-code
        run: |
          cd scripts/workflow
          bash exit_code.sh
