name: Pash-Benchmark-Tests
on: 
  pull_request_target:
    types: [assigned, opened, synchronize, reopened]



paths: 
    - compiler/**
    - runtime/**
    - evaluation/**
    - annotations/**


# Jobs section
jobs:
    Pash-Tests:
      strategy:
        matrix:
          os: 
            - ubuntu-18.04
            - ubuntu-20.04
            #- debian #stable-20210408
      runs-on: ${{ matrix.os }}
            
      steps:
        - uses: actions/checkout@v2 
        - name: Running-Pash-Benchmarks
          run: |
            git clone https://github.com/andromeda/pash
            cd pash
            bash scripts/distro-deps.sh
            bash scripts/setup-pash.sh
            export PASH_TOP=$PWD
            export PATH=$PATH:$PASH_TOP
            cd scripts
            bash run_tests.sh  
            cd workflow
            bash parse.sh > results.log 2>&1  
            # get the timer in english
            date=$(LANG=en_us_88591; date)
            echo "VERSION<<EOF" >> $GITHUB_ENV
            echo  "OS:${{matrix.os}}" >> $GITHUB_ENV
            echo -e "$date\n" >> $GITHUB_ENV
            # Parses the results and construct a github message post
            # we append the data to the global env
            cat results.log >> $GITHUB_ENV
            echo 'EOF' >> $GITHUB_ENV
            
            
#        - uses: actions/github-script@v3
#        - name: Comment on PR
#          with:
#            script: |
#              github.issues.createComment({
#                issue_number: context.issue.number,
#                owner: context.repo.owner,
#                repo: context.repo.repo,
#                body: '${{ env.VERSION}}',
#              })
# 
#        - name: Exit-code
#        - run: |
#            cd scripts/workflow
#            bash exit_code.sh
