# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Jobs section
jobs:
    # The job that will use the container image you just pushed to ghcr.io
    super-job:
        runs-on: ubuntu-18.04
        container:
            image: dkarnikis/test:latest
        steps:
            - name: super-step
              uses: actions/checkout@v2
            
            - name: Install dependencies
              run: |
                
                find . -name "circle-ci-bot" -type d

 
            - name: pash
              shell: bash
              run: |
                cd /pash/
                git pull
                git checkout top-level-tests
                
            
            - name: test
              shell: bash
              run: |
                ls
                ls /
                ls ~/
                echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
                echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
                echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
                
                echo "--This is running in my custom Docker image--"
