# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for th
  push: 
    branches: [ main ]
  pull_request:
    branches: [ main ]
#    branches:    
#      - '*'         # matches every branch that doesn't contain a '/'
#      - '*/*'       # matches every branch containing a single '/'
#      - '**'        # matches every branch
#      - '!master'   # excludes master
#  push:
#    branches:
#    - '*'
#    - '!main'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Jobs section
jobs:
    # The job that will use the container image you just pushed to ghcr.
    super-job:
        runs-on: ubuntu-18.04
        container:
            image: dkarnikis/test:latest
        steps:
#          - uses: unsplash/comment-on-pr@master
          - uses: actions/checkout@v2 
          - name: Run pash
            run: |
              pw=$PWD                                           
              cd /pash/                                         
              git pull                                         
              git checkout top-level-tests                     
              cd scripts                                       
              #bash run_tests.sh                                
              #bash parse.sh > results.log 2>&1                 
              #VER=$(cat results.log | sed -z 's/\n/,/g' )
              #echo "VERSION=\"$VER\"" >> $GITHUB_ENV
              #echo "${{ env.VERSION }}"

              # get the timer in english
              date=$(LANG=en_us_88591; date)
              echo "$date\n" > haha
              echo hihi >> haha
              
              VER=$(cat haha)
              echo $VER
              echo "VERSION=$(cat haha)" >> $GITHUB_ENV
          - name: posting
            uses: unsplash/comment-on-pr@master

            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            with:
              msg: "${{ env.VERSION }}"
              check_for_duplicate_msg: false  # OPTIONAL 

  #
#            run: |                                              
#              echo $gev                                         
#              echo $URL                                         
#              echo $GITHUB_TOKEN
#              echo $GITHUB_CONTEXT
#              curl \                                            
#                -X POST \                                       
#                $URL \                                          
#                -H "Content-Type: application/json" \           
#                -H "Authorization: token $GITHUB_TOKEN" \       
#                --data '{ "body": "blah blah" }'                
                                                                
