# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Jobs section
jobs:
    # The job that will use the container image you just pushed to ghcr.io
    super-job:
        runs-on: ubuntu-18.04
        container:
            image: dkarnikis/test:latest
        steps:
            - name: super-step
              uses: actions/checkout@v2
            
            - name: Install dependencies
              run: |
                echo $PWD


 
            - name: pash
              shell: bash
              run: |
                cd /pash/
                git pull
                git checkout top-level-tests
                cd scripts
                #bash run_tests.sh
                #bash parse.sh > results.log 2>&1
                #cp results.log /
                #cd /
                #ls -la
            - name: Create or Update Comment
              uses: peter-evans/create-or-update-comment@v1.4.5
              with:
                issue-number: 1
                body: |
                    This is a multi-line test comment
                    - With GitHub **Markdown** :sparkles:
                    - Created by [create-or-update-comment][1]

                    [1]: https://github.com/peter-evans/create-or-update-comment
                    reactions: '+1'
