# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for th
  push: 
    branches-ignore: #[ main ]
      - 'main'
  pull_request:
    branches: [ main ]
#    branches:    
#      - '*'         # matches every branch that doesn't contain a '/'
#      - '*/*'       # matches every branch containing a single '/'
#      - '**'        # matches every branch
#      - '!master'   # excludes master
#  push:
#    branches:
#    - '*'
#    - '!main'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Jobs section
jobs:
    Pash-Tests:
        runs-on: ubuntu-18.04
        container:
            image: dkarnikis/test:latest
        steps:
#          - uses: unsplash/comment-on-pr@master
          - uses: actions/checkout@v2 
          - name: Running-Pash-Benchmarks
            run: |
              pw=$PWD                                           
              cd /pash/                                         
              git pull                                         
              git checkout top-level-tests                     
              cd scripts                                       
              bash run_tests.sh                                
              bash parse.sh > results.log 2>&1                 
              # get the timer in english
              date=$(LANG=en_us_88591; date)
              FINAL=$(cat /proc/cpuinfo)
              echo $FINAL              
              echo "VERSION<<EOF" >> $GITHUB_ENV
              echo "$date\n" >> $GITHUB_ENV
              cat results.log >> $GITHUB_ENV
              echo 'EOF' >> $GITHUB_ENV

          - name: Posting Results
            uses: unsplash/comment-on-pr@master

            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            with:
              msg: "${{ env.VERSION }}"
              check_for_duplicate_msg: false
          - name: Exit-code
            run: |
              cd /pash/scripts/
              bash exit_code.sh
         
